services:
  app: &app
    build:
      context: .
      target: development
      args:
        - RUBY_VERSION=3.0
    command: bundle exec rake
    volumes:
      - ./:/opt/app
    tty: true
    stdin_open: true
    env_file:
      - .env

  test:
    <<: *app
    command: bundle exec rspec --format documentation
    profiles:
      - test
    env_file:
      - .env.test


networks:
  default:
    name: projects
    external: true
    ipam:
      driver: default
      config:
        - subnet: "69.0.0.0/24"
